server:
  port: 11110
  servlet:
    context-path: "/electron/example"

dubbo:
  application:
    name: electron
    owner: dome

  provider:
    timeout: 30000
    retries: 0

  registry:
    address: N/A
    register: false
    subscribe: true
electron:
    registry: etcd://124.223.198.143:2379
    applicationName: test-springmvc
    userInfoClass: com.lamp.electron.example.service.example.UserInfo